#!/bin/zsh

a='schroot --chroot=cross-lmi'

b='cd /opt/lmi/bin'
c='LMI_COMPILER=gcc ; LMI_TRIPLET=i686-w64-mingw32 ; . /opt/lmi/src/lmi/set_toolchain.sh'
d='wine ./lmi_wx_shared --ash_nazg --data_path=/opt/lmi/data'
e='/opt/lmi/src/lmi/gui_test.sh'

print -rs $b ; echo $b ; eval $b
print -rs $c ; echo $c
print -rs $d ; echo $d
print -rs $e ; echo $e

unset a
unset b
unset c
unset d
unset e
