#!/bin/zsh

a='schroot --chroot=cross-lmi'

b='cd /opt/lmi/bin'
c='wine ./lmi_wx_shared --ash_nazg --data_path=/opt/lmi/data --pyx=only_new_pdf'
d='wine ./wx_test --ash_nazg --data_path=/opt/lmi/data --pyx=only_new_pdf'

print -rs $b ; echo $b ; eval $b
print -rs $c ; echo $c
print -rs $d ; echo $d

unset a
unset b
unset c
unset d

