#!/bin/zsh

a='schroot --chroot=lmi'

b='cd /opt/lmi/src/lmi'
d='make $coefficiency check_concinnity 2>&1 |less -S -N'
e='sed -f diagnostics.sed ../log 2>&1 |less -S'
f='pushd /tmp; /opt/lmi/src/lmi/test_schemata.sh 2>&1 |less; popd'

print -rs $b ; echo $b ; eval $b
print -rs $d ; echo $d
print -rs $e ; echo $e
print -rs $f ; echo $f

unset a
unset b
unset d
unset e
unset f
