#!/bin/sh

set -vx

CHROOT_USERS=$(getent group "lmi" | cut -d':' -f4 | tr ',' ' ')
#CHROOT_UIDS=
for u in ${CHROOT_USERS}; do
  echo "${u}" "$(id -u "${u}")"
  CHROOT_UIDS="${CHROOT_UIDS} $(id -u "${u}")"
done
CHROOT_UIDS=$(echo "${CHROOT_UIDS}" | sed -e's/^ //')
echo "'${CHROOT_USERS}'"
echo "'${CHROOT_UIDS}'"

i=0
for i in 1 2 3 4; do
  echo "${CHROOT_UIDS}" | cut -d' ' -f"${i}"
done

echo "${CHROOT_UIDS}" | cut -d' ' -f1
echo "${CHROOT_UIDS}" | cut -d' ' -f2
echo "${CHROOT_UIDS}" | cut -d' ' -f3
echo "${CHROOT_UIDS}" | cut -d' ' -f4

i=1
while [ "$i" -ne 10 ]
do
  uid=$(echo "${CHROOT_UIDS}" | cut -d' ' -f"${i}")
  user=$(echo "${CHROOT_USERS}" | cut -d' ' -f"${i}")
  printf '  user %i: name %s; uid %i\n' "$i" "$user" "$uid"
  i=$((i + 1))
done
