#!/bin/zsh

a='schroot --chroot=cross-lmi'

b='cd /opt/lmi/src/lmi'
c='git ls-files --deleted | xargs git checkout --'
u='eval `ssh-agent`'
v='ssh-agent $SHELL'
w='ssh-add ~/.ssh/id_rsa'
x='ssh-add -D'
y='ssh-agent -k > /dev/null 2>&1'

print -rs $b ; echo $b ; eval $b
print -rs $c ; echo $c
# 'ssh-agent' not presently used in chroot:
#print -rs $u ; echo $u ; eval $u
#echo $w >/dev/clipboard
#print -rs $v ; echo $v ; eval $v
# This wouldn't affect the spawned shell:
#print -rs $w ; echo $w ; eval $w
#print -rs $x ; echo $x ; eval $x
#print -rs $y ; echo $y ; eval $y

unset a
unset b
unset c
unset u
unset v
unset w
unset x
unset y
