#!/bin/zsh

a='schroot --chroot=lmi'

b='cd /opt/lmi/src/lmi'
c='git ls-files --deleted | xargs -t git checkout --'
d='for z in *(m-1) ; do touch --reference=$z /opt/lmi/free/src/lmi/$z; done'
e='make $coefficiency LMI_COMPILER=gcc LMI_TRIPLET=x86_64-pc-linux-gnu check_concinnity 2>&1 |less -S -N'
u='eval `ssh-agent`'
v='ssh-agent $SHELL'
w='ssh-add ~/.ssh/id_rsa'
x='ssh-add -D'
y='ssh-agent -k > /dev/null 2>&1'

print -rs $b ; echo $b ; eval $b
print -rs $c ; echo $c
print -rs $d ; echo $d
print -rs $e ; echo $e
# 'ssh-agent' not presently used in chroot:
#print -rs $u ; echo $u ; eval $u
# /dev/clipboard is a cygwinism, though GNU/Linux alternatives exist
#echo $w >/dev/clipboard
#print -rs $v ; echo $v ; eval $v
# This wouldn't affect the spawned shell:
#print -rs $w ; echo $w ; eval $w
#print -rs $x ; echo $x ; eval $x
#print -rs $y ; echo $y ; eval $y

unset a
unset b
unset c
unset d
unset e
unset u
unset v
unset w
unset x
unset y
