#!/bin/sh

# git commit-msg hook

# Copyright (C) 2016 Gregory W. Chicares.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
#
# http://savannah.nongnu.org/projects/lmi
# email: <gchicares@sbcglobal.net>
# snail: Chicares, 186 Belle Woods Drive, Glastonbury CT 06033, USA

set -e

sed_script='
1{/\.$/{s/^.*$/Do not end first line with period/p}}
2{/^$/!{s/\(^.*$\)/Second line "\1" not empty./p}}
/.\{73\}/s/\(^.*$\)/\1 exceeds 72 characters/p
'

printf "checking commit message..."

z=$(sed -n -e "$sed_script" "$1")

if [ -n "$z" ]; then
    printf '\n%b\n' "$z"
    printf "COMMIT ABORTED\n"
    exit 1
fi

printf "okay\n"
